### ISSUE TITLE
Able to search without giving radius.

### ISSUE THREAD

**Issue by jeroen-meijer** [jsjambar/Project7#4]
It's really confusing, see;
![image](https://user-images.githubusercontent.com/14292245/27787068-e02a410a-5fe3-11e7-8d31-b92acaad5785.png)
![image](https://user-images.githubusercontent.com/14292245/27787099-038fc746-5fe4-11e7-841d-901e997c1b8b.png)

Pls fix.

Mvg, Jeroen.

**Comment by jsjambar** [comment]
Fixed with the following commit:
https://github.com/jsjambar/Project7/commit/baa6029ebae6b01634cf837084ae3f473d51d281
